name: Make docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This cancels any such job that is still runnning
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2
    # Install Python
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pdoc -U
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install skeletor
      run: |
        pip install -e .
    - name: Build docs
      run: |
        pdoc -o ./docs skeletor
    - name: Change index.html
      run: |
        cp ./docs/skeletor.html ./docs/index.html
    # Configure Github
    - name: setup git config
      run: |
        # setup the username and email.
        git config user.name "GitHub Actions"
        git config user.email "<>"
    # Commit changes
    - name: commit
      run: |
        # Stage the file, commit and push
        git add ./docs
        git commit -m "build docs"
        git push origin master
